Repository thenewboston-developers/Website, pull requests merged in 2020-11, with the labels that each got.

#480 hello world in chinese
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#489 Download page fix
  src/containers/Download/index.tsx
Labels: Not Paid

#623 Added Hello World in Punjabi
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#642 Add hello world in javanese
  src/containers/Home/HomeHero/hello-world.ts
Labels: 500

#649 Add hello world in Amharic
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#647 Bug/#645 team lead text alignment issue
  src/containers/Teams/TeamMemberCard/TeamMemberCard.scss
Labels: Review In Progress

#652 Hellow World in Belarusian
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#656 WageeshaEB
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#655 Added Yiddish Hello World
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#651 Added Hello World In Nepali
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#646 #643 - Fix readme spelling mistakes and grammar
  README.md
Labels: Not Paid

#650 Docs update
  README.md
Labels: Not Paid

#684 Add Serbian language
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#691 Added "Hello World" in isiNdebele
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#567 Added Hello World in Malay Language
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#712 added hello world in avaric
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#711 added hello world for Armenian language
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#709 Improve Tamil translation of Hello World
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#708 Hello world in Frisian
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#713 Added Afrikaans language
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#701 Added Hello World in Assamese
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#689 Add Hello World in Xhosa.
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#740 :globe_with_meridians: Added Hello World in Uzbek language
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#735 zulu hello world
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#727 added Hello World in bulgarian
  src/containers/Home/HomeHero/hello-world.ts
  yarn.lock
Labels: Not Paid

#725 Added Hello World in Bihari languages (Bhojpuri)
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#720 Adding Hello World in Irish/Gaelic language
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#690 Fixed a typo in Albanian language Hello World
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#641 Fixes: #523 Assets page
  src/assets/images/TNB-Logo.png
  src/assets/images/TNB-LogoAndWordmark.png
  src/components/A/index.tsx
  src/components/Footer/index.tsx
  src/components/Icon/index.tsx
  src/components/TopNav/TopNav.scss
  src/components/TopNav/index.tsx
  src/containers/App.tsx
  src/containers/Assets/Assets.scss
  src/containers/Assets/index.tsx
  src/types/assets.ts
Labels: Review In Progress

#762 Added Czech language
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#677 Changed hello in telugu to real form of hello i.e namaste
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#765 Hello world in Polish
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#771 Added Maltese language.
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#820 Add Hello World Twi (Akan)
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#698 Update of hello-world.ts and a suggestion.
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#692 Hello world in Akan
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#884 Added Maori language
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#891 'Hello World', in Haitian Creole
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid

#987 Hello world Swedish correction
  .vs/slnx.sqlite
  src/containers/Home/HomeHero/hello-world.ts
Labels: Not Paid
